version: '3'
services:
  app:
    build: .
    tty: true
    volumes:
      - ".:/app"
      # exclude volumes
      - ex_git:/app/.git
    ports:
      - "3000:3000"
      - "9001:9001"
volumes:
  ex_git:
